giantswarm/cert-exporter

helm/cert-exporter-chart/templates/daemonset.yaml

See https://github.com/giantswarm/kubernetes-node-health/pull/8#issue-210170489

Set match labels

---

Dockerfile
exporters/cert/exporter.go
helm/cert-exporter-chart/templates/daemonset.yaml
main.go

Part of: https://github.com/giantswarm/giantswarm/issues/3986
Related: https://github.com/giantswarm/hive/pull/338
Add ability to scan multiple certificate paths (we have multiple cert location on Vault node)

Allow using multiple paths for certs

---

.circleci/config.yml

Towards giantswarm/giantswarm#4012
Deploy to a temporary quay channel which we can use to deploy from feature branches.

Publish to deploy channel

---

exporters/cert/exporter.go

Towards https://github.com/giantswarm/giantswarm/issues/4972

Adds support for ignoring private keys

---

Dockerfile
helm/cert-exporter-chart/templates/daemonset.yaml
helm/cert-exporter-chart/templates/psp.yaml
helm/cert-exporter-chart/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/5983

Switch to non-root user

---

README.md

This adds minimal metrics info to the README.

Add basic documentation about exposed metrics

---

CHANGELOG.md
helm/cert-exporter-chart/Chart.yaml
helm/cert-exporter-chart/templates/daemonset.yaml

Towards https://github.com/giantswarm/giantswarm/issues/6440

Tolerate all taints

---

.circleci/config.yml
integration/test/basic/project.yaml

Towards giantswarm/giantswarm#4606

Replace e2e-harness test with go test

---

.circleci/config.yml

Adding the export logs for all core component charts.

Export kind logs

---

.circleci/config.yml
.gitignore
helm/cert-exporter/Chart.yaml
helm/cert-exporter/templates/daemonset.yaml
helm/cert-exporter/templates/priorityclass.yaml
helm/cert-exporter/templates/psp.yaml
helm/cert-exporter/templates/rbac.yaml
helm/cert-exporter/templates/service-account.yaml
helm/cert-exporter/templates/service.yaml
helm/cert-exporter/values.yaml

Towards giantswarm/giantswarm#7029, specifically migrating core components to App Catalog.

Push cert-exporter to default app catalog

---

CHANGELOG.md
helm/cert-exporter-chart/templates/daemonset.yaml
helm/cert-exporter/templates/daemonset.yaml

Towards https://github.com/giantswarm/giantswarm/issues/6817

Remove CPU limits

---

helm/cert-exporter-chart/templates/priorityclass.yaml
helm/cert-exporter/templates/priorityclass.yaml
integration/templates/cert_exporter_values.go

Towards giantswarm/giantswarm#7675

Remove priorityclass as its created by helmclient

---

CHANGELOG.md
helm/cert-exporter/templates/daemonset.yaml

Towards https://github.com/giantswarm/roadmap/issues/30

Change daemonset to use release revision not time for Helm 3 support

---

CHANGELOG.md
pkg/project/project.go

Towards https://github.com/giantswarm/giantswarm/issues/10177

prepare release v1.2.3

---

CHANGELOG.md
helm/cert-exporter/templates/np.yaml

Tested to be working on KVM TC.

Add network policy for scraping

---

CHANGELOG.md
exporters/secret/exporter.go

CA certs in TLS secrets should also be checked for expiry.

check ca and tls certs in secrets

---

CHANGELOG.md
helm/cert-exporter/values.yaml

Set docker as the default registry

Change default registry

---

CHANGELOG.md
helm/cert-exporter/templates/daemonset.yaml
helm/cert-exporter/templates/deployment.yaml
helm/cert-exporter/values.yaml

towards https://github.com/giantswarm/giantswarm/issues/20618

make exporter args configurable in Helm chart

---

.circleci/config.yml

App is already included in provider default-apps and would lead to conflicts when installing.

Removed from CAPI app collections

---

.ats/main.yaml
.circleci/config.yml
.nancy-ignore
CHANGELOG.md
Pipfile
Pipfile.lock
helm/cert-exporter/templates/np-deployment.yaml
helm/cert-exporter/templates/np.yaml
helm/cert-exporter/templates/service-deployment.yaml
helm/cert-exporter/templates/service.yaml
helm/cert-exporter/templates/servicemonitor-deployment.yaml
helm/cert-exporter/templates/servicemonitor.yaml
helm/cert-exporter/values.yaml
tests/ats/Pipfile
tests/ats/Pipfile.lock
tests/ats/test_cert_exporter.py
tests/kind_config.yaml

Towards https://github.com/giantswarm/giantswarm/issues/27576

Add service monitor to cert-exporter

---

CHANGELOG.md
helm/cert-exporter/Chart.yaml
helm/cert-exporter/templates/daemonset-policy-exceptions.yaml
helm/cert-exporter/templates/deployment-policy-exceptions.yaml
helm/cert-exporter/templates/psp-deployment.yaml
helm/cert-exporter/templates/psp.yaml
helm/cert-exporter/templates/rbac-deployment.yaml
helm/cert-exporter/templates/rbac.yaml
helm/cert-exporter/values.schema.json
helm/cert-exporter/values.yaml

Issue: https://github.com/giantswarm/giantswarm/issues/28345

Replace PSP installation condition

---

CHANGELOG.md
helm/cert-exporter/templates/daemonset-policy-exceptions.yaml
helm/cert-exporter/templates/deployment-policy-exceptions.yaml
helm/cert-exporter/values.schema.json
helm/cert-exporter/values.yaml

Makes the Kyverno PolicyExceptions configurable

Make kyverno PolicyExceptions configurable

---

CHANGELOG.md
helm/cert-exporter/templates/deployment-policy-exceptions.yaml

Fixes the destination namespace for the deamonset policy

Fix PolicyException namespace

---

helm/cert-exporter/templates/daemonset-policy-exceptions.yaml
helm/cert-exporter/templates/deployment-policy-exceptions.yaml

Fixes both PolicyException namespaces since I made a mistake in the previous pr

Fixes Kyverno PolicyException namespaces and brings back capabilities verification

---

.circleci/config.yml
CHANGELOG.md
helm/cert-exporter/templates/daemonset.yaml
helm/cert-exporter/templates/deployment.yaml
helm/cert-exporter/templates/vpa-deployment.yaml
helm/cert-exporter/values.schema.json
helm/cert-exporter/values.yaml

Towards: https://github.com/giantswarm/roadmap/issues/3625
Adds resource configuration for the cert-exporter deployment and daemonset, adds VPA resource for the deployment (enabled by default).

Add VPA and resources configuration.

---

CHANGELOG.md
exporters/token/exporter.go

Towards: https://github.com/giantswarm/giantswarm/issues/33001

Fix linting issues

---

helm/cert-exporter/templates/daemonset-policy-exceptions.yaml
helm/cert-exporter/templates/deployment-policy-exceptions.yaml

I think this is all that's needed for the Kyverno API upgrade for each repo (starting with this one). I did run a `make test`, but if there's any other verification I can do, @Gacko @njuettner @yulianedyalkova definitely let me know!

upgrade kyverno policy exceptions to v2 api
